### ISSUE TITLE
Detect packages on MyGet as well

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.Serializers.CompatTests#4]
We currently only run on NuGet but it would be good to enable restoring from MyGet as well to allow us to verify packages before pushing.

We need to merge both NuGet and MyGet since not all packages we need is on our myget feed.

Unless we import the packages we need to myget?

**Comment by timbussmann** [comment]
can be closed as this is using our regular nuget config, including myget, since the rework.
